- name: Release Drafter
  # You may pin to the exact commit or the version.
  # uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb
  uses: release-drafter/release-drafter@v5.21.1
  with:
    # If your workflow requires multiple release-drafter configs it be helpful to override the config-name.
The config should still be located inside `.github` as that's where we are looking for config files.

    config-name: # optional, default is release-drafter.yml
    # The name that will be used in the GitHub release that's created or updated.
This will override any `name-template` specified in your `release-drafter.yml` if defined.

    name: # optional
    # The tag name to be associated with the GitHub release that's created or updated.
This will override any `tag-template` specified in your `release-drafter.yml` if defined.

    tag: # optional
    # The version to be associated with the GitHub release that's created or updated.
This will override any version calculated by the release-drafter.

    version: # optional
    # A boolean indicating whether the release being created or updated should be immediately published.

    publish: # optional, default is 
    # A boolean indicating whether the release being created or updated is a prerelease.

    prerelease: # optional, default is 
    # The object that the release should be created to point to.

    commitish: # optional, default is 
    # A string that would be added before the template body.

    header: # optional, default is 
    # A string that would be added after the template body.

    footer: # optional, default is 
    # A boolean indicating whether the releaser mode is disabled.

    disable-releaser: # optional, default is 
    # A boolean indicating whether the autolabeler mode is disabled.

    disable-autolabeler: # optional, default is 
